# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Buck Makes Internet...

description: not including this internet...
author:
  name: Buck O'Leary
  email: howardeoleary@gmail.com
  github: buck3000
  twitter: buckoleary
  linkedin: www.linkedin.com/profile/view?id=124608842
  bio: Web Developer / DBC Coach / Last Living Wizards Fan / Dogs over Cats 4eva.
  email_md5: 1c89998d27f60069f4f988d01c551aa7

categories_path: categories.html
tags_path: tags.html

BASE_PATH:
