# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true
markdown: kramdown


defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Buck Makes Internet...

description: not including this internet...
author:
  name: Buck O'Leary
  email: howardeoleary@gmail.com
  github: buck3000
  twitter: buckoleary
  linkedin: 
  bio: Writer / Full Stack Developer / Former DBC Coach + Vets Who Code Mentor / One of dozens of living Wizards fans / 4.9 Stars on WAG!
  email_md5: 1c89998d27f60069f4f988d01c551aa7

categories_path: categories.html
tags_path: tags.html

BASE_PATH:
